// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcResponse.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GrpcResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Heartbeat            uint32   `protobuf:"varint,2,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcResponse) Reset()         { *m = GrpcResponse{} }
func (m *GrpcResponse) String() string { return proto.CompactTextString(m) }
func (*GrpcResponse) ProtoMessage()    {}
func (*GrpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpcResponse_baa9ddc85aa2e18c, []int{0}
}
func (m *GrpcResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcResponse.Unmarshal(m, b)
}
func (m *GrpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcResponse.Marshal(b, m, deterministic)
}
func (dst *GrpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcResponse.Merge(dst, src)
}
func (m *GrpcResponse) XXX_Size() int {
	return xxx_messageInfo_GrpcResponse.Size(m)
}
func (m *GrpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcResponse proto.InternalMessageInfo

func (m *GrpcResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GrpcResponse) GetHeartbeat() uint32 {
	if m != nil {
		return m.Heartbeat
	}
	return 0
}

func init() {
	proto.RegisterType((*GrpcResponse)(nil), "protocol.GrpcResponse")
}

func init() { proto.RegisterFile("grpcResponse.proto", fileDescriptor_grpcResponse_baa9ddc85aa2e18c) }

var fileDescriptor_grpcResponse_baa9ddc85aa2e18c = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x2f, 0x2a, 0x48,
	0x0e, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x0e, 0x5c, 0x3c, 0xee, 0x48, 0xf2, 0x42, 0x42, 0x5c, 0x2c,
	0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x60, 0xb6, 0x90, 0x0c, 0x17,
	0x67, 0x46, 0x6a, 0x62, 0x51, 0x49, 0x52, 0x6a, 0x62, 0x89, 0x04, 0x13, 0x58, 0x02, 0x21, 0x90,
	0xc4, 0x06, 0x36, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x49, 0x72, 0xb6, 0xd2, 0x68, 0x00,
	0x00, 0x00,
}
